### ISSUE TITLE
Unable to get the copy/disconnect dropdown to show

### ISSUE THREAD

**Issue by lmvdz** [lorisleiva/solana-wallets-vue#22]
I am able to get my wallet connected, but when I click the button with my public key showing it doesn't show the copy/disconnect dropdown.

I am using Vite + VueJS 3

No errors in console

![](https://i.gyazo.com/2b1695a99fc9293500bfe61a960d9e9c.gif)

**Comment by lmvdz** [comment]
Figured out the issue... was actually opening up, but it was rendering in a Vuetify `<v-app-bar>` which has some overflow: none I think.

**Comment by lmvdz** [comment]
![image](https://user-images.githubusercontent.com/2179775/174447212-56e281c7-843d-4efe-b59d-edd7dff81848.png)

But it should be showing, but I can't see it

**Comment by lmvdz** [comment]
I ended up doing hacky css to fix this...

```vue
<template>
  <v-app>
    <!-- <v-navigation-drawer app> -->
      <!-- -->
    <!-- </v-navigation-drawer> -->

    <wallet-multi-button dark/>


    <v-app-bar app>
      <!-- -->
      <Logo :height="64" heightUnits="px" :width="64" widthUnits="px"/>
      <GithubLink :height="32" heightUnits="px" :width="32" widthUnits="px"/>
      <v-spacer/>
    </v-app-bar>

    <!-- Sizes your content based upon application components -->
    <v-main>
      
      <!-- Provides the application the proper gutter -->
      <v-container fluid>
        <!-- If using vue-router -->
        <router-view/>
      </v-container>
    </v-main>

    <v-footer app>
      <v-row>
        
      </v-row>
    </v-footer>
  </v-app>
  
</template>
```
```css
<style>

.swv-dropdown {
  position: absolute !important; right: 0px; top: 0px; z-index: 1008;
}

.swv-dropdown-list {
  top: 3.25em !important;
  right: 1em !important;
}

.swv-button-trigger {
  position: absolute !important; right: 0px; top: 0px; z-index: 1008; margin: .5em;
}

</style>
```
